FROM docker.io/library/alpine AS build

ARG NGINX_VERSION="1.25.3"
ARG OPENSSL_VERSION="3.0.12"
ARG ZLIB_VERSION="1.3"
ARG PCRE_VERSION="10.42"

RUN apk add --no-cache \
    alpine-sdk \
    findutils \
    gcc \
    libc-dev \
    linux-headers \
    make \
    openssl-dev \
    pcre2-dev \
    zlib-dev \
    && wget -O- https://hg.nginx.org/nginx/archive/release-${NGINX_VERSION}.tar.gz | tar xz \
    && cd nginx-release-${NGINX_VERSION} \
    && wget -O- https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz | tar xz \
    && wget -O- https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz | tar xz \
    && wget -O- https://github.com/PCRE2Project/pcre2/releases/download/pcre2-${PCRE_VERSION}/pcre2-${PCRE_VERSION}.tar.gz | tar xz \
    && ./auto/configure --with-pcre=./pcre2-${PCRE_VERSION} --with-zlib=zlib-${ZLIB_VERSION} --with-openssl=./openssl-${OPENSSL_VERSION} \
    --builddir=/build --prefix=/nginx \
    --with-cc-opt="-O2" --with-ld-opt="-s -static" \
    && make

FROM scratch

LABEL org.opencontainers.image.authors="scratchimg@itayziv.dev"

COPY --chown=0:0 --chmod=644 /etc /etc
COPY --chown=101:101 --chmod=644 nginx/ /nginx/
COPY --from=build --chown=101:101 --chmod=755 /build/nginx /nginx/sbin/nginx
COPY --chown=101:101 --chmod=644 index.html /www/html/index.html

STOPSIGNAL SIGQUIT

USER nginx
EXPOSE 8080

ENTRYPOINT [ "/nginx/sbin/nginx" ]
CMD [ "-g", "daemon off;" ]
